name: pool
version: 1.3.7-dev

description: A class for managing a finite pool of resources.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/pool

environment:
  sdk: '>=2.0.0-dev.17.0 <3.0.0'

dependencies:
  async: '>=1.4.0 <3.0.0'
  stack_trace: '>=0.9.2 <2.0.0'

dev_dependencies:
  fake_async: ^1.0.0
  pedantic: ^1.4.0
  test: ^1.0.0
