name: pool
version: 1.5.0-nullsafety.3

description: >-
  Manage a finite pool of resources.
  Useful for controlling concurrent file system or network requests.
homepage: https://github.com/dart-lang/pool

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  async: '>=2.5.0-nullsafety <2.5.0'
  stack_trace: '>=1.10.0-nullsafety <1.10.0'

dev_dependencies:
  fake_async: ^1.2.0-nullsafety
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
